/*
 * Generated by classgen, version 1.5
 * 11/14/13 12:53 PM
 */
package javacode.syntaxtree;

public class mjc_Identifier implements SyntaxNode 
{
	private SyntaxNode parent;
	public String s;

	public mjc_Identifier(String s) 
	{
		this.s = s;
	}

	public SyntaxNode getParent() 
	{
		return parent;
	}

	public void setParent(SyntaxNode parent) 
	{
		this.parent = parent;
	}

	public void accept(Visitor visitor) 
	{
		visitor.visit(this);
	}

	public void childrenAccept(Visitor visitor) 
	{
	}

	public void traverseTopDown(Visitor visitor) 
	{
		accept(visitor);
	}

	public void traverseBottomUp(Visitor visitor) 
	{
		accept(visitor);
	}

	public String toString() 
	{
		return s;
	}

	public String toString(String tab) 
	{
		return s;
	}
}
