/*
 * Generated by classgen, version 1.5
 * 11/18/13 11:57 AM
 */
package javacode.syntaxtree;

public class mjc_Block extends mjc_Statement {

  public mjc_StatementList sl;

  public mjc_Block (mjc_StatementList sl) {
    this.sl = sl;
    if (sl != null) sl.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (sl != null) sl.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (sl != null) sl.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (sl != null) sl.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("mjc_Block(\n");
      if (sl != null)
        buffer.append(sl.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [mjc_Block]");
    return buffer.toString();
  }
}
