/*
 * Generated by classgen, version 1.5
 * 11/18/13 11:57 AM
 */
package javacode.syntaxtree;

public class mjc_Program implements SyntaxNode {

  private SyntaxNode parent;
  public mjc_ClassDeclList cl;

  public mjc_Program (mjc_ClassDeclList cl) {
    this.cl = cl;
    if (cl != null) cl.setParent(this);
  }

  public SyntaxNode getParent() {
    return parent;
  }

  public void setParent(SyntaxNode parent) {
    this.parent = parent;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (cl != null) cl.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (cl != null) cl.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (cl != null) cl.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString() {
    return toString("");
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("mjc_Program(\n");
      if (cl != null)
        buffer.append(cl.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [mjc_Program]");
    return buffer.toString();
  }
}
