/*
 * Generated by classgen, version 1.5
 * 11/19/13 9:29 PM
 */

package javacode.syntaxtree;

public interface SyntaxNode extends VisitorNode {
  public SyntaxNode getParent();
  public void setParent(SyntaxNode parent);
}
