/*
 * Generated by classgen, version 1.5
 * 11/18/13 11:57 AM
 */

package javacode.syntaxtree;

public interface SyntaxNode extends VisitorNode {
  public SyntaxNode getParent();
  public void setParent(SyntaxNode parent);
}
