/*
 * Generated by classgen, version 1.5
 * 11/18/13 11:57 AM
 */

package javacode.syntaxtree;

public interface VisitorNode {
  public void accept(Visitor visitor);

  public void childrenAccept(Visitor visitor);
  public void traverseBottomUp(Visitor visitor);
  public void traverseTopDown(Visitor visitor);
}
