/*
 * Generated by classgen, version 1.5
 * 11/19/13 9:29 PM
 */
package javacode.syntaxtree;

public abstract class VisitorAdaptor implements Visitor {

  public void visit(mjc_ClassDeclList mjc_ClassDeclList) { visit(); }
  public void visit(mjc_ExpList mjc_ExpList) { visit(); }
  public void visit(mjc_FormalList mjc_FormalList) { visit(); }
  public void visit(mjc_MethodDeclList mjc_MethodDeclList) { visit(); }
  public void visit(mjc_StatementList mjc_StatementList) { visit(); }
  public void visit(mjc_VarDeclList mjc_VarDeclList) { visit(); }
  public void visit(mjc_Formal mjc_Formal) { visit(); }
  public void visit(mjc_Identifier mjc_Identifier) { visit(); }
  public void visit(mjc_Program mjc_Program) { visit(); }
  public void visit(mjc_VarDecl mjc_VarDecl) { visit(); }
  public void visit(mjc_ClassDecl mjc_ClassDecl) { visit(); }
  public void visit(mjc_ClassDeclExtends mjc_ClassDeclExtends) { visit(); }
  public void visit(mjc_ClassDeclSimple mjc_ClassDeclSimple) { visit(); }
  public void visit(mjc_Exp mjc_Exp) { visit(); }
  public void visit(mjc_And mjc_And) { visit(); }
  public void visit(mjc_ArrayLength mjc_ArrayLength) { visit(); }
  public void visit(mjc_ArrayLookup mjc_ArrayLookup) { visit(); }
  public void visit(mjc_CallExpression mjc_CallExpression) { visit(); }
  public void visit(mjc_DoubleEqual mjc_DoubleEqual) { visit(); }
  public void visit(mjc_GTEQ mjc_GTEQ) { visit(); }
  public void visit(mjc_LTEQ mjc_LTEQ) { visit(); }
  public void visit(mjc_NotEqual mjc_NotEqual) { visit(); }
  public void visit(mjc_False mjc_False) { visit(); }
  public void visit(mjc_IdentifierExp mjc_IdentifierExp) { visit(); }
  public void visit(mjc_IntegerLiteral mjc_IntegerLiteral) { visit(); }
  public void visit(mjc_StringLiteral mjc_StringLiteral) { visit(); }
  public void visit(mjc_NewArray mjc_NewArray) { visit(); }
  public void visit(mjc_NewObject mjc_NewObject) { visit(); }
  public void visit(mjc_Not mjc_Not) { visit(); }
  public void visit(mjc_Or mjc_Or) { visit(); }
  public void visit(mjc_This mjc_This) { visit(); }
  public void visit(mjc_Null mjc_Null) { visit(); }
  public void visit(mjc_True mjc_True) { visit(); }
  public void visit(mjc_Add mjc_Add) { visit(); }
  public void visit(mjc_Div mjc_Div) { visit(); }
  public void visit(mjc_GT mjc_GT) { visit(); }
  public void visit(mjc_LT mjc_LT) { visit(); }
  public void visit(mjc_Mult mjc_Mult) { visit(); }
  public void visit(mjc_Sub mjc_Sub) { visit(); }
  public void visit(mjc_Statement mjc_Statement) { visit(); }
  public void visit(mjc_ArrayAssign mjc_ArrayAssign) { visit(); }
  public void visit(mjc_Assign mjc_Assign) { visit(); }
  public void visit(mjc_Block mjc_Block) { visit(); }
  public void visit(mjc_CallStatement mjc_CallStatement) { visit(); }
  public void visit(mjc_If mjc_If) { visit(); }
  public void visit(mjc_Print mjc_Print) { visit(); }
  public void visit(mjc_While mjc_While) { visit(); }
  public void visit(mjc_Type mjc_Type) { visit(); }
  public void visit(mjc_BooleanType mjc_BooleanType) { visit(); }
  public void visit(mjc_IdentifierType mjc_IdentifierType) { visit(); }
  public void visit(mjc_IntArrayType mjc_IntArrayType) { visit(); }
  public void visit(mjc_StringArrayType mjc_StringArrayType) { visit(); }
  public void visit(mjc_IntegerType mjc_IntegerType) { visit(); }
  public void visit(mjc_StringType mjc_StringType) { visit(); }
  public void visit(mjc_MethodType mjc_MethodType) { visit(); }
  public void visit(mjc_MethodVoidType mjc_MethodVoidType) { visit(); }
  public void visit(mjc_MethodReturnType mjc_MethodReturnType) { visit(); }
  public void visit(mjc_MethodDecl mjc_MethodDecl) { visit(); }
  public void visit(mjc_MethodDeclSimple mjc_MethodDeclSimple) { visit(); }
  public void visit(mjc_MethodDeclStatic mjc_MethodDeclStatic) { visit(); }

  public void visit() { }

}
