/*
 * Generated by classgen, version 1.5
 * 11/19/13 9:29 PM
 */

package javacode.syntaxtree;

public interface VisitorNode {
  public void accept(Visitor visitor);

  public void childrenAccept(Visitor visitor);
  public void traverseBottomUp(Visitor visitor);
  public void traverseTopDown(Visitor visitor);
}
