/*
 * Generated by classgen, version 1.5
 * 11/14/13 12:53 PM
 */
package javacode.syntaxtree;

public class mjc_ClassDeclSimple extends mjc_ClassDecl {

  public mjc_Identifier i;
  public mjc_VarDeclList vl;
  public mjc_MethodDeclList ml;

  public mjc_ClassDeclSimple (mjc_Identifier i, mjc_VarDeclList vl, mjc_MethodDeclList ml) {
    this.i = i;
    if (i != null) i.setParent(this);
    this.vl = vl;
    if (vl != null) vl.setParent(this);
    this.ml = ml;
    if (ml != null) ml.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (i != null) i.accept(visitor);
    if (vl != null) vl.accept(visitor);
    if (ml != null) ml.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (i != null) i.traverseTopDown(visitor);
    if (vl != null) vl.traverseTopDown(visitor);
    if (ml != null) ml.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (i != null) i.traverseBottomUp(visitor);
    if (vl != null) vl.traverseBottomUp(visitor);
    if (ml != null) ml.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("mjc_ClassDeclSimple(\n");
      if (i != null)
        buffer.append(i.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (vl != null)
        buffer.append(vl.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (ml != null)
        buffer.append(ml.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [mjc_ClassDeclSimple]");
    return buffer.toString();
  }
}
