
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 03 19:24:33 EST 2013
//----------------------------------------------------

package javacode;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIV_TOK = 35;
  public static final int BEGINVARS_TOK = 2;
  public static final int EQ_TOK = 41;
  public static final int LPAREN_TOK = 23;
  public static final int RBRACE_TOK = 26;
  public static final int STRING_TOK = 17;
  public static final int SEMICOLON_TOK = 29;
  public static final int IF_TOK = 9;
  public static final int PUBLIC_TOK = 14;
  public static final int LBRACKET_TOK = 27;
  public static final int ELSE_TOK = 5;
  public static final int INTCONST_TOK = 46;
  public static final int LTEQ_TOK = 44;
  public static final int PLUS_TOK = 32;
  public static final int GT_TOK = 36;
  public static final int NEQ_TOK = 42;
  public static final int RPAREN_TOK = 24;
  public static final int STATIC_TOK = 16;
  public static final int THIS_TOK = 19;
  public static final int NULL_TOK = 13;
  public static final int RBRACKET_TOK = 28;
  public static final int TRUE_TOK = 20;
  public static final int CLASS_TOK = 4;
  public static final int AND_TOK = 40;
  public static final int EOF = 0;
  public static final int ENDVARS_TOK = 6;
  public static final int ASSIGN_TOK = 39;
  public static final int error = 1;
  public static final int MINUS_TOK = 33;
  public static final int COMMA_TOK = 30;
  public static final int PRINT_TOK = 18;
  public static final int DOT_TOK = 38;
  public static final int VOID_TOK = 21;
  public static final int NEW_TOK = 12;
  public static final int BOOLTYPE_TOK = 3;
  public static final int FALSE_TOK = 8;
  public static final int ID_TOK = 45;
  public static final int INTTYPE_TOK = 10;
  public static final int LENGTH_TOK = 11;
  public static final int BANG_TOK = 31;
  public static final int EXTENDS_TOK = 7;
  public static final int LBRACE_TOK = 25;
  public static final int RETURN_TOK = 15;
  public static final int STRCONST_TOK = 47;
  public static final int GTEQ_TOK = 43;
  public static final int WHILE_TOK = 22;
  public static final int LT_TOK = 37;
  public static final int MUL_TOK = 34;
  public static final int OR_TOK = 48;
}