/*
 * Generated by classgen, version 1.5
 * 11/19/13 9:29 PM
 */
package javacode.syntaxtree;

public class mjc_StringLiteral extends mjc_Exp {

  public String s;

  public mjc_StringLiteral (String s) {
    this.s = s;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("mjc_StringLiteral(\n");
    buffer.append("  "+tab+s);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [mjc_StringLiteral]");
    return buffer.toString();
  }
}
