/*
 * Generated by classgen, version 1.5
 * 11/19/13 9:29 PM
 */
package javacode.syntaxtree;

public interface Visitor {

  public void visit(mjc_ClassDeclList mjc_ClassDeclList);
  public void visit(mjc_ExpList mjc_ExpList);
  public void visit(mjc_FormalList mjc_FormalList);
  public void visit(mjc_MethodDeclList mjc_MethodDeclList);
  public void visit(mjc_StatementList mjc_StatementList);
  public void visit(mjc_VarDeclList mjc_VarDeclList);
  public void visit(mjc_Formal mjc_Formal);
  public void visit(mjc_Identifier mjc_Identifier);
  public void visit(mjc_Program mjc_Program);
  public void visit(mjc_VarDecl mjc_VarDecl);
  public void visit(mjc_ClassDecl mjc_ClassDecl);
  public void visit(mjc_ClassDeclExtends mjc_ClassDeclExtends);
  public void visit(mjc_ClassDeclSimple mjc_ClassDeclSimple);
  public void visit(mjc_Exp mjc_Exp);
  public void visit(mjc_And mjc_And);
  public void visit(mjc_ArrayLength mjc_ArrayLength);
  public void visit(mjc_ArrayLookup mjc_ArrayLookup);
  public void visit(mjc_CallExpression mjc_CallExpression);
  public void visit(mjc_DoubleEqual mjc_DoubleEqual);
  public void visit(mjc_GTEQ mjc_GTEQ);
  public void visit(mjc_LTEQ mjc_LTEQ);
  public void visit(mjc_NotEqual mjc_NotEqual);
  public void visit(mjc_False mjc_False);
  public void visit(mjc_IdentifierExp mjc_IdentifierExp);
  public void visit(mjc_IntegerLiteral mjc_IntegerLiteral);
  public void visit(mjc_StringLiteral mjc_StringLiteral);
  public void visit(mjc_NewArray mjc_NewArray);
  public void visit(mjc_NewObject mjc_NewObject);
  public void visit(mjc_Not mjc_Not);
  public void visit(mjc_Or mjc_Or);
  public void visit(mjc_This mjc_This);
  public void visit(mjc_Null mjc_Null);
  public void visit(mjc_True mjc_True);
  public void visit(mjc_Add mjc_Add);
  public void visit(mjc_Div mjc_Div);
  public void visit(mjc_GT mjc_GT);
  public void visit(mjc_LT mjc_LT);
  public void visit(mjc_Mult mjc_Mult);
  public void visit(mjc_Sub mjc_Sub);
  public void visit(mjc_Statement mjc_Statement);
  public void visit(mjc_ArrayAssign mjc_ArrayAssign);
  public void visit(mjc_Assign mjc_Assign);
  public void visit(mjc_Block mjc_Block);
  public void visit(mjc_CallStatement mjc_CallStatement);
  public void visit(mjc_If mjc_If);
  public void visit(mjc_Print mjc_Print);
  public void visit(mjc_While mjc_While);
  public void visit(mjc_Type mjc_Type);
  public void visit(mjc_BooleanType mjc_BooleanType);
  public void visit(mjc_IdentifierType mjc_IdentifierType);
  public void visit(mjc_IntArrayType mjc_IntArrayType);
  public void visit(mjc_StringArrayType mjc_StringArrayType);
  public void visit(mjc_IntegerType mjc_IntegerType);
  public void visit(mjc_StringType mjc_StringType);
  public void visit(mjc_MethodType mjc_MethodType);
  public void visit(mjc_MethodVoidType mjc_MethodVoidType);
  public void visit(mjc_MethodReturnType mjc_MethodReturnType);
  public void visit(mjc_MethodDecl mjc_MethodDecl);
  public void visit(mjc_MethodDeclSimple mjc_MethodDeclSimple);
  public void visit(mjc_MethodDeclStatic mjc_MethodDeclStatic);

}
